# Generated by Django 4.0.6 on 2022-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to='quiz_create/images'),
        ),
    ]
